# Stremio Node 18.x
FROM node:18-alpine AS build

RUN apk add --update --no-cache git

# Install app dependencies
WORKDIR /app
COPY . /app
RUN npm ci

RUN npm run build 

FROM nginx:1.23-alpine

# Meta
LABEL Description="Stremio Web" Vendor="Smart Code OOD" Version="1.0.0"

COPY --from=build /app/build /usr/share/nginx/html
